// <auto-generated />
using System;
using AssemblyService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssemblyService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250318112040_migration_01")]
    partial class migration_01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AssemblyService.Models.AssembleModel", b =>
                {
                    b.Property<int>("vehicle_id")
                        .HasColumnType("int");

                    b.Property<int>("NIC")
                        .HasColumnType("int");

                    b.Property<int>("assignee_id")
                        .HasColumnType("int");

                    b.Property<string>("attachment_path")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<bool>("isCompleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("vehicle_id", "NIC");

                    b.ToTable("assembles");
                });
#pragma warning restore 612, 618
        }
    }
}
